org: sofkp
service: comentario

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::322906775818:role/LabRole

functions:
  crear_review:
    handler: CrearReview.lambda_handler
    events:
      - http:
          path: /review/create
          method: post
          cors: true
          integration: lambda

  listar_reviews:
    handler: ListarReview.lambda_handler
    events:
      - http:
          path: /review/list
          method: get
          cors: true
          integration: lambda

  actualizar_review:
    handler: ActualizarReview.lambda_handler
    events:
      - http:
          path: /comment/update
          method: patch
          cors: true
          integration: lambda

  eliminar_review:
    handler: EliminarReview.lambda_handler
    events:
      - http:
          path: /comment/delete
          method: delete
          cors: true
          integration: lambda

  get_review:
    handler: GetReview.lambda_handler
    events:
      - http:
          path: /comment/get
          method: get
          cors: true
          integration: lambda
