org: fruit
service: serviciocliente

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::943073974505:role/LabRole

functions:
  crear_review:
    handler: CrearReview.lambda_handler
    events:
      - http:
          path: /review/create
          method: post
          cors: true
          integration: lambda

  listar_reviews:
    handler: ListarReview.lambda_handler
    events:
      - http:
          path: /review/list
          method: get
          cors: true
          integration: lambda

  actualizar_review:
    handler: ActializarReview.lambda_handler
    events:
      - http:
          path: /review/answer
          method: patch
          cors: true
          integration: lambda

  eliminar_review:
    handler: EliminarReview.lambda_handler
    events:
      - http:
          path: /review/delete
          method: delete
          cors: true
          integration: lambda
