org: fruit
service: comentario

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE_ARN}
  environment:
    TABLE_NAME: arn:aws:iam::943073974505:role/LabRole

functions:
  crear_review:
    handler: CrearReview.lambda_handler
    events:
      - http:
          path: /review/create
          method: post
          cors: true
          integration: lambda

  listar_reviews:
    handler: ListarReview.lambda_handler
    events:
      - http:
          path: /review/list
          method: get
          cors: true
          integration: lambda

  actualizar_review:
    handler: ActualizarReview.lambda_handler
    events:
      - http:
          path: /comment/update
          method: patch
          cors: true
          integration: lambda

  eliminar_review:
    handler: EliminarReview.lambda_handler
    events:
      - http:
          path: /comment/delete
          method: delete
          cors: true
          integration: lambda

resources:
  Resources:
    CommentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: pr_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: pr_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: tenant_id-user_id-index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: user_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL