version: '3.8'

services:
  swagger-usuarios:
    image: swaggerapi/swagger-ui
    container_name: swagger-usuarios
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /app/swagger.yaml
    volumes:
      - ./lambdas/login/swagger.yml:/app/swagger.yaml

  swagger-productos:
    image: swaggerapi/swagger-ui
    container_name: swagger-productos
    ports:
      - "8082:8080"
    environment:
      SWAGGER_JSON: /app/swagger.yaml
    volumes:
      - ./lambdas/producto/swagger.yaml:/app/swagger.yaml

swagger-orden:
    image: swaggerapi/swagger-ui
    container_name: swagger-orden
    ports:
      - "8083:8080"
    environment:
      SWAGGER_JSON: /app/swagger.yaml
    volumes:
      - ./lambdas/orden/swagger.yaml:/app/swagger.yaml

swagger-comentario:
    image: swaggerapi/swagger-ui
    container_name: swagger-comentario
    ports:
      - "8084:8080"
    environment:
      SWAGGER_JSON: /app/swagger.yaml
    volumes:
      - ./lambdas/comentario/swagger.yaml:/app/swagger.yaml

swagger-inventario:
    image: swaggerapi/swagger-ui
    container_name: swagger-inventario
    ports:
      - "8085:8080"
    environment:
      SWAGGER_JSON: /app/swagger.yaml
    volumes:
      - ./lambdas/inventario/swagger.yaml:/app/swagger.yaml

  swagger-pagos:
    image: swaggerapi/swagger-ui
    container_name: swagger-pagos
    ports:
      - "8086:8080"
    environment:
      SWAGGER_JSON: /app/swagger.yaml
    volumes:
      - ./lambdas/pagos/swagger.yaml:/app/swagger.yaml

  swagger-customizations:
    image: swaggerapi/swagger-ui
    container_name: swagger-customizations
    ports:
      - "8087:8080"
    environment:
      SWAGGER_JSON: /app/swagger.yaml
    volumes:
      - ./lambdas/customizations/swagger.yaml:/app/swagger.yaml