org: fruit
service: api-customization

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::943073974505:role/LabRole

  environment:
    BUCKET_NAME: dev-multishop-logos

functions:
  # GET /customization/{tenant_id}
  getCustomization:
    runtime: nodejs22.x
    handler: getCustomization.handler
    events:
      - http:
          path: /customization/{tenant_id}
          method: get
          cors: true
          integration: lambda

  # PATCH /customization/{tenant_id}
  updateCustomization:
    handler: updateCustomization.lambda_handler
    events:
      - http:
          path: /customization/{tenant_id}
          method: patch
          cors: true
          integration: lambda

  # POST /customization
  createCustomization:
    handler: createCustomization.lambda_handler
    events:
      - http:
          path: /customization
          method: post
          cors: true
          integration: lambda

  # DELETE /customization/{tenant_id}
  deleteCustomization:
    runtime: nodejs22.x
    handler: deleteCustomization.handler
    events:
      - http:
          path: /customization/{tenant_id}
          method: delete
          cors: true
          integration: lambda

  # POST /customization/upload-logo
  uploadLogo:
    handler: uploadLogo.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /customization/upload-logo
          method: post
          cors: true
          integration: lambda

  # GET /customization/list-logos
  getTenantLogos:
    runtime: nodejs22.x
    handler: getTenantLogos.handler
    events:
      - http:
          path: /customization/list-logos
          method: get
          cors: true
          integration: lambda
