org: flaqq
service: login

provider:
  name: aws
  runtime: python3.12	
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::975050197903:role/LabRole

functions:
  crear_usuario:
    handler: crear_usuario.lambda_handler
    events:
      - http:
          path: /user/register
          method: post
          cors: true
          integration: lambda

  login_usuario:
    handler: login_usuario.lambda_handler
    events:
      - http:
          path: /user/login
          method: post
          cors: true
          integration: lambda

  validar_token:
    handler: validar_token.lambda_handler
    events:
      - http:
          path: /token/validate
          method: post
          cors: true
          integration: lambda
