org: fruit
service: orden

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE_ARN}
  environment:
    ORDERS_TABLE_NAME: pf_ordenes
    PRODUCTS_TABLE_NAME: pf_productos
    INVENTORY_TABLE_NAME: pf_inventario

functions:
  crear_orden:
    handler: CrearOrden.lambda_handler
    events:
      - http:
          path: /orden/create
          method: post
          cors: true
          integration: lambda

  buscar_ordenes:
    handler: BuscarOrden.lambda_handler
    events:
      - http:
          path: /orden/get
          method: get
          cors: true
          integration: lambda

  actualizar_orden:
    handler: ActualizarOrden.lambda_handler
    events:
      - http:
          path: /orden/update
          method: patch
          cors: true
          integration: lambda

  list_orden:
    handler: ListarOrden.lambda_handler
    events:
      - http:
          path: /orden/list
          method: get
          cors: true
          integration: lambda

  delete_orden:
    handler: EliminarOrden.lambda_handler
    events:
      - http:
          path: /orden/delete
          method: delete
          cors: true
          integration: lambda

resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ORDERS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: order_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: order_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: tenant_id-user_id-index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: user_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: user_id-order_id-index
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: order_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL