org: fruit
service: orden

provider:
  name: aws
  runtime: python3.12
  memorySize: 256
  timeout: 30
  iam:
    role: arn:aws:iam::943073974505:role/LabRole

functions:
  crear_orden:
    handler: CrearOrden.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /orden/create
          method: post
          cors: true
          integration: lambda

  listar_ordenes:
    handler: ListarOrdenes.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /orden/list
          method: get
          cors: true
          integration: lambda

  actualizar_orden:
    handler: ActualizarOrden.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /orden/update
          method: patch
          cors: true
          integration: lambda