org: fruit
service: serviciocliente

provider:
  name: aws
  runtime: python3.12
  memorySize: 256
  timeout: 30
  iam:
    role: arn:aws:iam::943073974505:role/LabRole

functions:
  crear_review:
    handler: CrearReview.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /review/create
          method: post
          cors: true
          integration: lambda

  listar_reviews:
    handler: ListarReviews.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /review/list
          method: get
          cors: true
          integration: lambda

  answer_review:
    handler: AnswerReview.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /review/answer
          method: patch
          cors: true
          integration: lambda

  eliminar_review:
    handler: EliminarReview.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /review/delete
          method: delete
          cors: true
          integration: lambda
