org: flaqq
service: inventario

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::687417073285:role/LabRole

functions:
  crear_inventario:
    handler: CrearInventario.lambda_handler
    events:
      - http:
          path: /inventory/create
          method: post
          cors: true
          integration: lambda

  actualizar_stock: # #
    handler: ActualizarStock.lambda_handler
    events:
      - http:
          path: /inventory/stock/update
          method: patch
          cors: true
          integration: lambda
 
  add_producto_stock:
    handler: IngresarProductoInventario.lambda_handler
    events:
      - http:
          path: /inventory/product/add
          method: post
          cors: true
          integration: lambda

  listar_productos_inventario: 
    handler: ListarInventario.lambda_handler
    events:
      - http:
          path: /inventory/products/list
          method: get
          cors: true
          integration: lambda

  get_stock: 
    handler: GetStock.lambda_handler
    events:
      - http:
          path: /inventory/stock
          method: get
          cors: true
          integration: lambda

  eliminar_producto: 
    handler: EliminarProductoInventario.lambda_handler
    events:
      - http:
          path: /inventory/product/delete
          method: delete
          cors: true
          integration: lambda

  listar_inventario_nombre: 
    handler: GetInventariosNombres.lambda_handler
    events:
      - http:
          path: /inventory/names # #
          method: get
          cors: true
          integration: lambda
