org: fruit
service: pagos

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE_ARN}
  environment:
    ORDERS_TABLE_NAME: pf_ordenes
    PAYMENTS_TABLE_NAME: pf_pagos

functions:
  crear_pago:
    handler: CrearPago.lambda_handler
    events:
      - http:
          path: /pago/create
          method: post
          cors: true
          integration: lambda

  listar_pagos:
    handler: ListarPagos.lambda_handler
    events:
      - http:
          path: /pago/list
          method: get
          cors: true
          integration: lambda

  buscar_pago:
    handler: BuscarPago.lambda_handler
    events:
      - http:
          path: /pago/search
          method: get
          cors: true
          integration: lambda

  delete_pago:
    handler: EliminarPago.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /pago/delete
          method: delete
          cors: true
          integration: lambda

resources:
  Resources:
    PaymentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PAYMENTS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: pago_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: pago_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: tenant_id-user_id-index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: user_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: user_id-pago_id-index
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: pago_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
