org: flaqq
service: pagos

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::975050197903:role/LabRole

functions:
  crear_pago:
    handler: CrearPago.lambda_handler
    events:
      - http:
          path: /pago/create
          method: post
          cors: true
          integration: lambda

  listar_pagos:
    handler: ListarPagos.lambda_handler
    events:
      - http:
          path: /pago/list
          method: get
          cors: true
          integration: lambda

  buscar_pago:
    handler: BuscarPago.lambda_handler
    events:
      - http:
          path: /pago/search
          method: get
          cors: true
          integration: lambda

  delete_pago:
    handler: EliminarPago.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /pago/delete
          method: delete
          cors: true
          integration: lambda
