org: sofkp
service: producto

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::322906775818:role/LabRole

functions:
  crear_producto:
    handler: CrearProducto.lambda_handler
    events:
      - http:
          path: /product/create
          method: post
          cors: true
          integration: lambda

  listar_productos:
    handler: ListarProductos.lambda_handler
    events:
      - http:
          path: /product/list
          method: get
          cors: true
          integration: lambda

  actualizar_producto:
    handler: ActualizarProducto.lambda_handler
    events:
      - http:
          path: /product/update
          method: patch
          cors: true
          integration: lambda

  buscar_producto:
    handler: BuscarProducto.lambda_handler
    events:
      - http:
          path: /product/search
          method: get
          cors: true
          integration: lambda

  eliminar_producto:
    handler: EliminarProducto.lambda_handler
    events:
      - http:
          path: /product/delete
          method: delete
          cors: true
          integration: lambda
  
  get_producto_photo:
    handler: GetProductoFoto.lambda_handler
    events:
      - http:
          path: /product/foto
          method: get
          cors: true
          integration: lambda

